name: poker-chip-split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pyyaml
  - numpy
  - tqdm
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - setuptools
  - wheel
  - build
  - pip:
    - pre-commit
    - -e .
